"""Add admin, active, password reset to User, system flag to Transaction"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.sql import text as sa_text # <-- You added this import

# revision identifiers, used by Alembic.
revision = '586cb24ca295'         # <-- THIS LINE IS CRUCIAL
down_revision = '84e143002c8d'    # <-- This links it to the previous migration
branch_labels = None              # <-- This is usually None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        # Modify the 'is_system' column addition
        batch_op.add_column(sa.Column('is_system', sa.Boolean(),
                                     nullable=False,
                                     server_default=sa_text('0') # Add server_default for False
                                    ))

    with op.batch_alter_table('user', schema=None) as batch_op:
        # Modify the 'is_admin' column addition
        batch_op.add_column(sa.Column('is_admin', sa.Boolean(),
                                     nullable=False,
                                     server_default=sa_text('0') # Add server_default for False
                                    ))
        # Modify the 'is_active' column addition
        batch_op.add_column(sa.Column('is_active', sa.Boolean(),
                                     nullable=False,
                                     server_default=sa_text('1') # Add server_default for True
                                    ))
        # Modify the 'password_reset_required' column addition
        batch_op.add_column(sa.Column('password_reset_required', sa.Boolean(),
                                     nullable=False,
                                     server_default=sa_text('0') # Add server_default for False
                                    ))

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('password_reset_required')
        batch_op.drop_column('is_active')
        batch_op.drop_column('is_admin')

    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('is_system')

    # ### end Alembic commands ###