"""Add sector to Asset model

Revision ID: 84e143002c8d
Revises: d7c44bf6e949
Create Date: 2025-04-23 05:22:36.195069

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e143002c8d'
down_revision = 'd7c44bf6e949'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sector', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('sector')

    # ### end Alembic commands ###
