"""Add company_name, total_value, portfolio_asset

Revision ID: d7c44bf6e949
Revises: 
Create Date: 2025-04-17 15:31:51.288502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7c44bf6e949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.add_column(sa.Column('company_name', sa.String(length=100), nullable=True))

    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_value', sa.Float(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('portfolio', schema=None) as batch_op:
        batch_op.drop_column('total_value')

    with op.batch_alter_table('asset', schema=None) as batch_op:
        batch_op.drop_column('company_name')

    # ### end Alembic commands ###
